A2SV/Terra

.vscode/settings.json, backend/Application.Tests/Features/Users/RegisterUser/ForgotPasswordCommandHandlerTest.cs, backend/Application/Features/Accounts/ForgotPassword/Command/ForgotPasswordCommand.cs, backend/Application/Features/Accounts/ForgotPassword/Command/ForgotPasswordHandler.cs
​
> Implement ForgotPassword Test
The test is in two parts:
* When the user does not exist
* When the user exists.​
​
​
​It checks the validity of the ForgotPasswordHandler
=> Ggpp 165 implement forgot password functionality

backend/Application/Features/Accounts/ForgotPassword/Command/ForgotPasswordHandler.cs
​
> Fix reset-url in the ForgotPasswordHandler
​
​
​
​
> Affect the forgot password controller
​
​
​
​
​
​
​
​
​
​
​
> Do you have any relevant URLs or Wiki pages that could help give background information for the changes in this Pull-Request? These are usually StackOverflow posts, Notion wiki pages, Wikipedia …
=> fix-reset-url

backend/Application/Contracts/IStorageService.cs, backend/Infrastructure/Infrastructure.csproj, backend/Infrastructure/StorageService/StorageService.cs, backend/WebApi/Controllers/FileController.cs, backend/WebApi/Filters/FileUploadOperationFilter.cs, backend/WebApi/Program.cs, backend/WebApi/WebApi.csproj
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​ …
=> Ggpp 201 implement image and video upload functionality

backend/Infrastructure/StorageService/StorageService.cs
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​ …
=> fix(backend): change google credential file path

mobile/lib/main.dart, mobile/lib/src/core/theme/common_color.dart, mobile/lib/src/features/dashboard/presentation/pages/add_listing_photos.dart
​
> Worked on Media page doe add listing
​
​
​
​
> affects the entire application
​
​
​
​
> no testing needed
​
​
​
​
​
​
​
> Do you have any relevant URLs or Wiki pages that could help give background information for the changes in this Pull-Request? These are usually StackOverflow posts, Notion wiki pages, Wikipedia articles, or links to APIs and Documentation of third-party packages.
​
- ...
=> mobile(feat) design add listing media page

backend/Infrastructure/StorageService/StorageService.cs
​
> change google creddential path
​
​
​
​
> the deployed version of the file service
​
​
​
​
​
​
​
​
​
​
​
> Do you have any relevant URLs or Wiki pages that could help give background information for the changes in this Pull-Request? These are usually StackOverflow posts, Notion wiki pages, Wikipedia articles, …
=> fix(backend): change google credential path

backend/Application/Contracts/IListingRepository.cs, backend/Application/Features/Listings/Dtos/GetAllListingDto.cs, backend/Application/Features/Listings/Dtos/PropertyDto.cs, backend/Application/Features/Listings/Dtos/PropertyPhotoDto.cs, backend/Application/Features/Listings/Dtos/PropertyVideoDto.cs, backend/Application/Features/Listings/Queries/GetAllListings/GetAllListingsQuery.cs, backend/Application/Features/Listings/Queries/GetAllListings/GetAllListingsQueryHandler.cs, backend/Domain/Enums/ResidentialOrCommercial.cs, backend/Persistence/Repositories/ListingRepository.cs
​
> Add media to get all listing response
​
​
​
​
> Whole team working on get all listings
​
​
​
​
> Tested on Db
​
​
​
​
​
​
​
> Do you have any relevant URLs or Wiki pages that could help give background information for the changes in this Pull-Request? These are usually StackOverflow posts, Notion wiki pages, Wikipedia articles, or links to APIs and Documentation of third-party packages.
​
- ...
=> Fix null values in get all listing functionality

mobile/ios/Runner/AppDelegate.swift, mobile/lib/src/features/auth/data/data_sources/auth_remote_data_source.dart, mobile/lib/src/features/auth/data/models/UserModel.dart, mobile/lib/src/features/auth/data/models/user_model.dart, mobile/lib/src/features/auth/data/repositories/auth_repository_impl.dart, mobile/lib/src/features/auth/domain/entities/entities.dart, mobile/lib/src/features/auth/domain/entities/user_entity.dart, mobile/pubspec.lock
​​​This pull request is being made to implement the refactoring of the `UserEntity` and `UserModel` classes within the mobile application. The primary change ensures that the UserModel now extends UserEntity and includes only the necessary fields (id, email, firstName, lastName) without additional sensitive data like passwords. 
​
​​The changes impact the mobile directory, specifically in the `auth` feature. Within the `auth` feature directory, it has also impacted the `auth_repository_impl.dart` file.
​
​
=> feat(mobile): refactor user entity and model

mobile/lib/src/core/entities/user_account.dart, mobile/lib/src/core/error/exception.dart, mobile/lib/src/core/use_case/use_case.dart, mobile/lib/src/features/auth/data/data_sources/auth_remote_data_source.dart, mobile/lib/src/features/auth/data/models/user_model.dart, mobile/lib/src/features/auth/data/repositories/auth_repository_impl.dart, mobile/lib/src/features/auth/domain/repositories/auth_repository.dart, mobile/lib/src/features/auth/domain/use_cases/auth_use_cases.dart, mobile/lib/src/features/auth/domain/use_cases/login_use_case.dart, mobile/lib/src/features/auth/domain/use_cases/register_with_email_password_use_case.dart, mobile/lib/src/features/auth/domain/use_cases/resend_otp.dart, mobile/lib/src/features/auth/domain/use_cases/verify_otp.dart, mobile/lib/src/features/dashboard/domain/use_cases/get_listings_use_case.dart, mobile/pubspec.lock
​The task involves refactoring the usecase.dart class to an abstract interface, updating the authDataSource methods to return Future<UserModel>, ensuring internet connectivity checks in the repository, and implementing error handling for ServerException.
​
​
This will affect how usecases can be implemented and how the repositories responds to different errors
​
​
​
​No tests were written
=> GGPP-247-Refactor-Use-Cases-and-Data-Source-Implementation

mobile/lib/src/features/auth/domain/use_cases/register_with_email_password_use_case.dart, mobile/lib/src/features/auth/domain/use_cases/resend_otp.dart, mobile/lib/src/features/auth/domain/use_cases/verify_otp.dart, mobile/lib/src/features/auth/presentation/bloc/bloc/authentication_state.dart, mobile/lib/src/features/auth/presentation/pages/password_reset.dart, mobile/lib/src/features/auth/presentation/pages/register_page.dart, mobile/lib/src/features/auth/presentation/pages/sign_in_page.dart, mobile/lib/src/features/auth/presentation/widgets/filter_button.dart, mobile/lib/src/features/auth/presentation/widgets/user_review_card.dart, mobile/lib/src/features/dashboard/data/repositories/dashboard_repository_impl.dart, mobile/lib/src/features/dashboard/presentation/pages/add_listing_contact_info.dart, mobile/lib/src/features/dashboard/presentation/pages/add_listing_location.dart, mobile/lib/src/features/onboarding/presentation/pages/otp_page.dart, mobile/pubspec.lock, mobile/test/src/features/auth/data/data_sources/auth_remote_data_source_test.dart
​
​This PR refactors functions from their regular return types to async/await, which improves code readability and ensures consistent handling of asynchronous operations.
​
​
​This PR impacts the parts of the codebase where asynchronous operations were previously handled without async/await. It refactors functions for more robust async handling, which may affect the Auth, Dashboard, and User features.
​
​
​
​No testing required for this task
​
​
​
> What Jira items (Epics, Stories, Tasks, or Sub-Tasks) are specifically related to this work? If this only …
=> refactored fubctions with regular return type to async/await

.gitignore, backend/Persistence/Configurations/PropertyDbContext.cs, backend/Persistence/Migrations/20241127201200_FixInheritance.Designer.cs, backend/Persistence/Migrations/20241127201200_FixInheritance.cs, backend/Persistence/Migrations/PropertyDbContextModelSnapshot.cs
​
​This pull request mains to solve discriminator inheritance uses from EntityFramework.
apply Fix_inheritance migration to see changes
​
​
​
​We move from a STI (single table inheritance) to a TPT (table per type) inheritance for modularity and scalability
​
​
​
​
​
​
​
> What Jira items (Epics, Stories, Tasks, or Sub-Tasks) are specifically related to this work? If this only covers a single item, there's no reason to list its parents. There should always be at least one Jira item, but if you have relevant Slack threads you can put them here as well. …
=> backend(fix): fixed schema inheritance

backend/WebApi/Program.cs
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​ …
=> backend(fix): remove forwarded header options

mobile/ios/Podfile.lock, mobile/lib/src/core/routes/app_routes.dart, mobile/lib/src/features/dashboard/presentation/pages/add_listing.dart, mobile/lib/src/features/dashboard/presentation/pages/add_listing_location.dart, mobile/lib/src/features/dashboard/presentation/pages/add_listing_photos.dart, mobile/lib/src/features/dashboard/presentation/pages/add_listing_res_hotel.dart, mobile/lib/src/features/dashboard/presentation/pages/dashboard.dart, mobile/pubspec.lock
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​ …
=> Ggpp 264 connect add listing pages

backend/Application/Contracts/IListingRepository.cs, backend/Application/Features/Listings/Commands/UpdatePropertyMarketStatus/UpdatePropertyMarketStatusCommand.cs, backend/Application/Features/Listings/Commands/UpdatePropertyMarketStatus/UpdatePropertyMarketStatusCommandHandler.cs, backend/Persistence/Repositories/ListingRepository.cs, backend/WebApi/Controllers/ListingController.cs
​
​Adding a market status update endpoint to mark property as reneted, available, unavailable or sold
​
​
​Improves application performance and maintenance
​
​
​
​
​
​
​
​
​
- …
=> backend(feat): Implement property market status update feature

mobile/lib/src/core/routes/app_routes.dart, mobile/lib/src/features/dashboard/presentation/pages/chat_page.dart, mobile/lib/src/features/dashboard/presentation/pages/dashboard.dart, mobile/lib/src/features/dashboard/presentation/pages/prof_page.dart, mobile/lib/src/features/dashboard/presentation/pages/saved_pages.dart, mobile/pubspec.lock
​
Implemented a persistent bottom navigation bar that will allow users to switch between pages seamlessly. Added AppRoutes for contact, saved and profile pages to ensure that each individual pages are routed as desired.
​
​
​
This feature directly impacts the DashboardPage and its associated navigation logic, ensuring smooth transitions between pages.This enhances navigation by allowing users to seamlessly switch between key sections of the app (Home, Chat, Add Listing, Saved, and Profile).​
​
=> feat(mobile): implement bottom navigation bar for listings page

backend/Application/Application.csproj, backend/Infrastructure/EmailService/EmailService.cs, backend/Infrastructure/Infrastructure.csproj
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​ …
=> backend(feat): add working email sender

backend/Application/Features/Accounts/RegisterUser/RegisterUserCommandHandler.cs, backend/Application/Features/Accounts/ResendOTP/ResendOTPCommandHandler.cs
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​ …
=> feat(backend) : Fix backend

web/components/Authentication/OtpVerification.tsx, web/components/Authentication/SignupCard.tsx
​
> otp hotfixes
​
​
​
​
Web
​
​
​
=> Ggpp 266 auth hot fixes

web/app/single/page.tsx, web/components/Listing/Cards/ContactCard.tsx, web/components/Listing/HeroListing.tsx, web/components/Listing/ListDesc.tsx, web/components/Listing/Review.tsx, web/components/Sliders/ImageCarousel2/EmblaCarousel.tsx, web/next.config.mjs
Mobile responsiveness for Single listing page
=> made single listing page mobile and ipad responsive

backend/Application/Contracts/IAmenityRepository.cs, backend/Application/Contracts/IListingRepository.cs, backend/Application/Features/Listings/Commands/UpdateListing/UpdateListingCommand.cs, backend/Application/Features/Listings/Commands/UpdateListing/UpdateListingCommandHandler.cs, backend/Persistence/Repositories/AmenityRepository.cs, backend/Persistence/Repositories/ListingRepository.cs, backend/WebApi/Controllers/ListingController.cs
Developed a new API endpoint to allow users to update existing listings. 
This change introduces the ability for users to update listing details through the API. It primarily impacts the listings module and related database interactions. The changes will affect users interacting with the API, ensuring smoother modification workflows.
=> Ggpp 261 implement update listing endpoint

backend/Application/Contracts/ITokenRepository.cs, backend/Application/Features/Accounts/Dtos/ResetPasswordDto.cs, backend/Application/Features/Accounts/ForgotPassword/Command/ForgotPasswordHandler.cs, backend/Application/Features/Accounts/ResetPassword/ResetPasswordCommand.cs, backend/Application/Features/Accounts/ResetPassword/ResetPasswordHandler.cs, backend/Persistence/Repositories/TokenRepository.cs, backend/WebApi/Controllers/AuthController.cs
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​ …
=> backend(fix): reset password flow

web/components/Common/Auth/Checkbox.tsx
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​ …
=> fix(web):jwt to cookies

web/components/AddListing/Features/ResidentialSubtype/ResidentialSpecific.tsx, web/components/AddListing/GeneralInfo.tsx, web/components/AddListing/GoogleMapComponent.tsx, web/components/AddListing/LocationForm.tsx, web/components/AddListing/SubmitButton.tsx, web/components/Listing/HeroListing.tsx, web/components/Listing/ListDesc.tsx, web/test/ListDesc.test.tsx, web/test/OtpVerification.test.tsx, web/tsconfig.json
This Pull-Request addresses multiple enhancements and fixes related to the add-listing functionality, including the completion of enum mappings, detailed error messages, and improvements to the Google Maps integration.
​
​
​
The changes affect the add-listing functionality, specifically the form data handling, enum mappings, error messages, and Google Maps integration. These changes will impact the user experience when adding a new listing, ensuring that all necessary features are included, errors are detailed, and the map functionality is reliable.
​
​
​
​
No test component
- Verifying that all necessary features are included in the form data.
- Ensuring that enum mappings are complete and accurate.
- Testing the add-listing functionality end-to-end.
- Checking that error messages …
=> Ggpp 290 single listing update functionality

mobile/lib/src/core/utils/currency_formatter.dart, mobile/lib/src/features/dashboard/domain/entities/enums.dart, mobile/lib/src/features/dashboard/presentation/pages/list_detail.dart, mobile/lib/src/features/dashboard/presentation/widgets/listings_card.dart, mobile/pubspec.lock
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​
​ …
=> feat(mobile): Implement function to format listing price

web/components/Authentication/ResetInputEmail.tsx, web/components/ContactUs/ContactUsDetails.tsx, web/render.yaml
=> added render.yaml, fixed linting issues

web/components/Authentication/ResetInputEmail.tsx, web/components/ContactUs/ContactUsDetails.tsx, web/components/General/Navbar.tsx, web/render.yaml
=> Deploy web

README.md, web/README.md
Added names and LinkedIn profile links to README under contributors
=> Webcontributorsbranch

web/.husky/pre-commit, web/components/Authentication/ResetInputEmail.tsx, web/components/ContactUs/ContactUsDetails.tsx, web/components/General/Navbar.tsx, web/jest.config.ts, web/render.yaml
update jest config, update pre commit to handle code coverage
=> Jest Config
